### GET GET GET GET GET GET GET GET GET GET GET GET GET GET GET GET GET GET 
GET http://localhost:4004/index/Teacher?$expand=subject

###

GET http://localhost:4004/index/Teacher
?$expand=subject($expand=subject)
#?$expand=subject,subject/teacher

####

### GET GET GET GET GET GET GET GET GET GET GET GET GET GET GET GET GET GET GET GET GET GET 
GET http://localhost:4004/index/Subject$ HTTP/1.1